### ISSUE TITLE
Load Patient Data

### ISSUE THREAD

**Issue by bpmweel** [FEDMix/eshmun#24]
## Story
As a Clinician
I want to select a directory to load a patients data
So that I can continue to the orthogonal view screen

## Proposed work
- Button on the first screen that allows you to open a directory
- After selecting the directory go to the orthogonal view screen.
- Actual Loading should be done on the orthogonal view screen
- Proposed Directory Structure (Depends on project):
  - [patient_ID]
     - [scans]
     - [annotations]
         - [annotation_1]
         - [annotation_2] 

## Acceptance Criteria
- [x] Add test to CI

**Comment by geek-yang** [comment]
We created a separate class to take care of the path to the patient data based on the specific folder tree. A corresponding test function is added to the test module inside our QT app.

These changes have been made based on the need for orthogonal view component related tasks. Therefore, for the pull request, we need to discuss whether this will need to be merged by the orthogonal view work first, or it makes sense to raise a pull request directly.

The changes are located under the branch "feature/load-patient-data" for review.
